dist: bionic
language: elixir

elixir:
  - "1.10"
  - "1.11"

opt_release:
  - "22.3"
  - "23.0"

env:
  global:
    - MIX_ENV=test
  jobs: 
    - BEFORE_INSTALL=""
    - BEFORE_INSTALL="mix deps.unlock --all"

before_install: $BEFORE_INSTALL

before_script:
  - mix local.rebar --force

script: mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
